# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
        ('quotes', '0002_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
        migrations.AddField(
            model_name='quotes',
            name='favorite',
            field=models.ManyToManyField(related_name='fav_by', to='log_reg.Users'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
